name: ci
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
      - run: yarn install --immutable
      - run: yarn compile
      - run: yarn format:all:check
      - run: yarn build
    timeout-minutes: 15
